### ISSUE TITLE
Здравствуйте плагин с версии 2023.1 не работает выходит ошибка как можно это исправить или когда выйдет обновление

### ISSUE THREAD

**Issue by nizom333** [saundefined/bitrix-idea#1]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/28598438/230612567-964685a7-911d-4813-9cca-09bdafe6a2e5.png">

**Comment by saundefined** [comment]
Добрый день,

Новая версия с 16 марта на модерации в JetBrains,

пока можно установить обновление вручную:
https://github.com/saundefined/bitrix-idea/releases/tag/v2023.1.0

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4685504/230612992-c9fcfd01-9726-4b5c-ae4b-c5f4aba1146f.png">

**Comment by nizom333** [comment]
Спасибо большое
