### ISSUE TITLE
Просит обновление плагина

### ISSUE THREAD

**Issue by nizom333** [saundefined/bitrix-idea#12]
![image](https://github.com/saundefined/bitrix-idea/assets/28598438/82bf18ef-a28a-4e60-b526-eafc8afc8159)

можете пожалуйста подсказать как можно установить новую версию плагина

**Comment by saundefined** [comment]
Подскажите, пожалуйста, какая у вас версия PhpStorm?

**Comment by nizom333** [comment]
Здравствуйте вроде версия 2023.3 самая последная

**Comment by saundefined** [comment]
Странно, у последней версии поддержка 2022.3 – 2023.3.

У вас плагин установлен с помощью ссылки `https://jetbrains.sergeypanteleev.com/updatePlugins.xml`?

Сможете посмотреть точный билд PhpStorm?
<img width="436" alt="image" src="https://github.com/saundefined/bitrix-idea/assets/4685504/5f98508f-45f0-4f18-a51d-460268e2f273">

Попробую разобраться

**Comment by nizom333** [comment]
Спасибо большое я с гитхаба скачивал последний раз после этого не обновлял сейчас новое версия оказывается вышло установил заработало еще раз спасибо
