### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by lasaczka** [saundefined/bitrix-idea#15]
Add build instructions, e. g. `gradle build`

**Comment by saundefined** [comment]
Hi,

you can use `./gradlew buildPlugin` to build plugin manually,
this command will build the plugin, but without connecting the bitrix core.

For bitrix autocomplete to work as well, before building, you need to put actual core files (for example, from the bxApiDocs project) to the `src/main/resources/bitrix-idea-library` path.
